### ISSUE TITLE
ParamValidationError: Parameter validation failed: Missing required parameter in input: "solutionVersionArn" Unknown parameter in input: "solutionArn", must be one of: name, solutionVersionArn, updateMode

### ISSUE THREAD

**Issue by rohanhodarkar** [aws-samples/amazon-personalize-samples#10]
As per notification in AWS Personalize console, I have updated service JSON files.
After updating and adding to the model I am facing below error while creating campaign:
```
create_campaign_response = personalize.create_campaign(
    name = "d3-recommendation-v2-1",
    solutionArn = solution_arn,
    updateMode = "MANUAL"
)

campaign_arn = create_campaign_response['campaignArn']
print (json.dumps(create_campaign_response, indent=2))
```

> ParamValidationError: Parameter validation failed:
> Missing required parameter in input: "solutionVersionArn"
> Unknown parameter in input: "solutionArn", must be one of: name, solutionVersionArn, updateMode

Seems like previously required parameter 'solutionArn' has been removed and 'solutionVersionArn' parameter is added. However the method which creates this solution in python SDK - 'personalize.create_solution' does not send back solution version ARN but only the Solution ARN.
See below output of 'personalize.create_solution' method.
![image](https://user-images.githubusercontent.com/19485472/53570012-77540a00-3b8b-11e9-833b-ece005d474a2.png)

Currently I have to manually go to the console and get the solution version ARN and use in my python code to create the campaigns.

Please add functionality to send solution version ARN from personalize.create_solution method.

Thanks,
Rohan Hodarkar

**Comment by easyj2j** [comment]
Yes, CreateCampaign was updated to require solutionVersionArn. Call [DescribeSolution](https://docs.aws.amazon.com/personalize/latest/dg/API_DescribeSolution.html), passing in solutionArn. solutionVersionArn will be under latestSolutionVersion in the response. Note, for the time being, you must call CreateCampaign with updateMode = "MANUAL".
