### ISSUE TITLE
Missing KMS kms:CreateKey on resource: *

### ISSUE THREAD

**Issue by omerh** [aws-samples/amazon-personalize-samples#115]
When trying to run the notebook [Best_Clientside_Security_Practices](https://github.com/aws-samples/amazon-personalize-samples/blob/master/getting_started/notebooks/Best_Clientside_Security_Practices.ipynb) in the step that creates KMS key the notebook role doesn't have the appropriate permissions.

when looking on the cloudformation at <https://amazon-personalize-github-samples.s3.amazonaws.com/PersonalizeDemo.yaml> it needs to have for the demo purpose a CreateKey policy 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "kms:CreateKey",
            "Resource": "*"
        }
    ]
}
```

**Comment by luseloso** [comment]
The issue has been fixed, the template now has "arn:aws:iam::aws:policy/AWSKeyManagementServicePowerUser" managed policy attached to it
