### ISSUE TITLE
Use real time events

### ISSUE THREAD

**Issue by ghost** [aws-samples/amazon-personalize-samples#116]
Hello there, 
I am trying to use personalize with real time event. When I push a bank csv file (with no header) to S3 and tried to use amplify to connect with personalize. But I do not know when I can ready build a model because if I choose a recipe then I got an error that I need 10000 records to ready. 

Could you suggest me some ways to do it?

Thanks in advance!

**Comment by annainspace** [comment]
Hi, 

The requirements for training a model is to have 1000 records of combined interaction data (after filtering by eventType and eventValueThreshold, if provided). This information can be found in the documentation [here](https://docs.aws.amazon.com/personalize/latest/dg/recording-events.html#recording-events-requirements). 

You can use an [event tracker](https://docs.aws.amazon.com/personalize/latest/dg/API_CreateEventTracker.html) and a call to the [PutEvents operation](https://docs.aws.amazon.com/personalize/latest/dg/API_UBS_PutEvents.html) to record your interactions.

After you have collected 1000+ interactions, you can chose a recipe and train a model.

**Comment by oanhsaitec** [comment]
Thank you @annainspace,

I am wondering how can I know that I reach to 1000 records when I use event tracker only (that means no historical record in S3 before)

**Comment by annainspace** [comment]
Hi,

You can use an [AWS lambda](https://aws.amazon.com/lambda/), together with [CloudWatch](https://aws.amazon.com/cloudwatch/) to track your ingestion. 

Another option is to periodically [export the interactions dataset](https://docs.aws.amazon.com/personalize/latest/dg/export-data.html) and check how many events have been recorded.
