### ISSUE TITLE
Create solution version

### ISSUE THREAD

**Issue by sciarrilli** [aws-samples/amazon-personalize-samples#13]
After the personalize.create_solution() method there is a step missing which is personalize.create_solution_version().

Looks like this was recently added.

**Comment by rohanhodarkar** [comment]
You do not need create_solution_version() for the process. This is optional step.
personalize.create_solution() itself creates default version which can be directly used in the campaigns.
[Check this answer.](https://github.com/aws-samples/amazon-personalize-samples/issues/10#issuecomment-471597708)

**Comment by easyj2j** [comment]
With the recent change, create_solution() just creates the configuration used to train the model. It no longer kicks off a training session. You have to call create_solution_version() for that.
