### ISSUE TITLE
CreateRecommender with custom domain to use Start Stop Recommender

### ISSUE THREAD

**Issue by DaviYokogawa** [aws-samples/amazon-personalize-samples#136]
When I'm trying to create a recommender via Command Line, I receive an raise saying "Please use a domains-specific Dataset Group to create the Recommender", but I set my dataset group domain as Custom.

![Screen Shot 2022-06-29 at 16 28 01](https://user-images.githubusercontent.com/52435393/176519917-476ed5c8-4979-4f23-a227-b72e40abaa4e.png)

<img width="1042" alt="Screen Shot 2022-06-29 at 16 38 28" src="https://user-images.githubusercontent.com/52435393/176522151-f8df3162-f4ed-4577-800d-9414098748e7.png">

I don't know if I understand, but to use the GetRecommendations we need to create a solution or create a recommender, but the option to stop the solution doesn't exists, so when I try to create a recommender was raised this error, so I'm in this loop, if I try to use Solution, I can't use the Start Stop Recommender to reduce my billing costs, and if I try to create a recommender I can't because I'm using a custom solution(I don't know if is it, but my hypothesis is, the Personalize only accept VIDEO_ON_DEMAND and ECOMMERCE)

I don't know if this helps, but when I try to list the recipes, we only have domains in ECOMMERCE recipes, and maybe this is broken

![Screen Shot 2022-06-29 at 16 37 58](https://user-images.githubusercontent.com/52435393/176521954-c84f97e2-4a1a-4dbd-8c24-344c6d1e84ad.png)

**Comment by seashman** [comment]
There are two different workflows in Amazon Personalize, a workflow for Domain dataset groups and a workflow for custom dataset groups. If you create a custom dataset group, you can't create domain based resources like recommenders. For custom dataset groups, you create a solution, then a solution version, and finally deploy a solution version with a campaign. You provide the campaign ARN when you get recommendations. See https://docs.aws.amazon.com/personalize/latest/dg/personalize-workflow.html.
