### ISSUE TITLE
Using a User's information about which other list of Users it is following within AWS Personalize Recipe

### ISSUE THREAD

**Issue by amanalok88** [aws-samples/amazon-personalize-samples#155]
Hi,

I am using AWS Personalize to build a personalized recommender system using a social networking application's data. I had the below question:

- Is there a way to introduce the effect of following another User by a given User.
- Essentially should it have an impact the personalized feed of a User, given the User follows a list of other Users ? 
- If yes, what should be the impact, in what magnitude, and how do we use this "User Following Other Users" information within Amazon Personalize.

Thanks!

**Comment by james-jory** [comment]
Take a look at the following blog post:

https://aws.amazon.com/blogs/machine-learning/attendee-matchmaking-at-virtual-events-with-amazon-personalize/
