### ISSUE TITLE
Dataset ignores 1st column

### ISSUE THREAD

**Issue by aggarwalpulkit** [aws-samples/amazon-personalize-samples#17]
It appears that even when the dataset's first column is user_id, the console keeps on complaining of missing that column in csv, however if rename first column to lets say just "id" and put user_id at a different position, then the upload to personalize works. This is a really annoying issue. I guess someone assumed there'll be an index column or primary key column as first in dataset whereas all examples and demos don't reflect it.

**Comment by chrisking** [comment]
Closing due to it being a pre-production issue. Have validated that the service works as expected with the user_id column now.
