### ISSUE TITLE
Misleading sample code?

### ISSUE THREAD

**Issue by danielvarga** [aws-samples/amazon-personalize-samples#18]
The documentation says that for HRNN models

> [...] you only provide user-id at inference. While the system does not throw an error if you also provide an item-id, the system neglects the value and the value does not impact the results.

In example code https://github.com/aws-samples/amazon-personalize-samples/blob/master/personalize_sample_notebook.ipynb?short_path=f7aa1a1#L1168 `itemId` is provided (and presumably neglected by the inference engine):

    get_recommendations_response = personalize_runtime.get_recommendations(
      campaignArn = campaign_arn,
      userId = str(user_id), 
      itemId = str(item_id)
    )

One consequence is that the results often look unreasonably bad in light of the ITEM that's printed:

    USER: 734
    ITEM: Roman Holiday (1953)
    Recommendations: [
      "Twister (1996)", 
      "Phenomenon (1996)", 
      "Birdcage, The (1996)", 
      "Mission: Impossible (1996)", 
      "Willy Wonka and the Chocolate Factory (1971)",

**Comment by yifeim** [comment]
It is okay to just remove the itemId like [this.](https://github.com/aws-samples/amazon-personalize-samples/blob/master/personalize_temporal_holdout/personalize_coldstart_demo.ipynb?short_path=c4aaa28#L1584) Would it be okay with you? If so, we will update the notebook.

**Comment by chrisking** [comment]
Great call out @danielvarga . We have removed the item_id from the request for clarity. Closing this issue.
