### ISSUE TITLE
roleArn

### ISSUE THREAD

**Issue by yifeim** [aws-samples/amazon-personalize-samples#42]
Missing roleArn in [2.View_Campaign_And_Interactions](https://github.com/aws-samples/amazon-personalize-samples/blob/master/getting_started/2.View_Campaign_And_Interactions.ipynb) and [personalize_sample_notebook](https://github.com/aws-samples/amazon-personalize-samples/blob/master/personalize_sample_notebook.ipynb).

**Comment by chrisking** [comment]
@yifeim can you specify where this is needed in the View campaign notebook?

**Comment by chrisking** [comment]
also it is definitely in the sample notebook as `role_arn`

**Comment by chrisking** [comment]
Could not reproduce, closing now.
