### ISSUE TITLE
diagnose.py should accept Timestamp units

### ISSUE THREAD

**Issue by PatrykMilewski** [aws-samples/amazon-personalize-samples#45]
When loading data from csv file, timestamps are not always in the same units (miliseconds, seconds or nanoseconds). This leads to raising errors - date is out of bounds.

To fix this, there should be an option, to specify datetime units:
diagnose.py:234
`df.index = df["TIMESTAMP"].values.astype("datetime64[ms]")`

My proposal is to add optional parameter to diagnose, diagnose_interactions, diagnose_items:
```
def diagnose(df, users=None, items=None, timestamp_units=None):
def diagnose_items(df, items, timestamp_units=None):
def diagnose_interactions(df, timestamp_units=None):
```
Or there should be global constant to define that.

**Comment by yifeim** [comment]
Personalize schema defines timestamp as long type with second unit. The
diagnostic scripts seek consensus with the api definition. This should be
better documented.

Do you need milliseconds? If so, please do that and suggest a feature
request on personalize support page with a brief description of the
scenario.

Thanks,
Yifei

**Comment by PatrykMilewski** [comment]
Yes, you are right, I was thinking about Personalize definition of Timestamp few hours after adding this issue, didn't noticed it enforces it as seconds before, thank you for response!

I think, that changing that makes no sense, since there are samples only for AWS Persoanlize service.
