### ISSUE TITLE
Which package do I need to install to run the metrics 'mean_reciprocal_rank'

### ISSUE THREAD

**Issue by PedroMBPinheiro** [aws-samples/amazon-personalize-samples#52]
I am using SageMaker jupyterLab with Conda_python3 kernel. 

I manage to pip install metrics, but it doe snot seem to be the right package.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f74f0bb2da8d> in <module>()
      1 from tqdm import tqdm_notebook
      2 import numpy as np
----> 3 from metrics import mean_reciprocal_rank, ndcg_at_k, precision_at_k

ImportError: cannot import name 'mean_reciprocal_rank'
---------------------------------------------------------------------------

What is the package name that should be installed?

**Comment by muralibalki** [comment]
There is a metrics.py in https://github.com/aws-samples/amazon-personalize-samples/blob/master/personalize_temporal_holdout/metrics.py . Make sure that is in path.
