### ISSUE TITLE
[Feature request] Add example of creating and using Filters

### ISSUE THREAD

**Issue by PatrykMilewski** [aws-samples/amazon-personalize-samples#73]
Hello,

As Personalize user I would like to see how to create Filters, use them with Campaign and how does they affect recommendations including changes after calling PersonalizeEvents.PutEvents API call:
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEvents.html

Thanks!

**Comment by luseloso** [comment]
Hello Patry,

What type of example specifically are you looking for? A notebook, lambda code?

Greetings.

**Comment by PatrykMilewski** [comment]
@luseloso Hey! Sorry for late response.

I needed an example, due to problems with filters, that in the end were caused by a bug in Personalize, which is now fixed. I believe examples in AWS docs are good enough, that's why I'm going to close this one. Thanks!
