### ISSUE TITLE
Batch Predictions with AWS Personalize

### ISSUE THREAD

**Issue by rohanhodarkar** [aws-samples/amazon-personalize-samples#8]
As per the [FAQ page](https://aws.amazon.com/personalize/faqs/), AWS Personalize provides batch recommendations along with real-time recommendations. 

> When deployed, developers call the service from their production services to get real-time or batch recommendations, and Amazon Personalize will automatically scale to meet demand. Once Amazon Personalize begins making inferences on production traffic, it measures the lift in engagement from personalization and generates reports in the AWS Console to allow developers to evaluate the model’s success. 

However I did not find any code where we can have batch recommendations.

Is it something in development?

**Comment by sethiv** [comment]
Batch recommendations is currently not available. We are correcting our FAQ section to reflect that.

**Comment by yifeim** [comment]
While batch recommendations is not available, an available work-around is to use a higher `minProvisionedTPS` in `create_campaign` and presumably turn it off after the batch recommendation job is finished.

**Comment by chrisking** [comment]
Closing due to it being answered for now.
