### ISSUE TITLE
Metrices in AWS Personalize console and Personalize SDK API get_matrics are different

### ISSUE THREAD

**Issue by rohanhodarkar** [aws-samples/amazon-personalize-samples#9]
I have noticed that Solution metric displayed in AWS Personalize console and personalize SDK API get_metric function are different for percision@k.

Which is correct?

Below are the snapshots:
AWS Personalize web console:
![console](https://user-images.githubusercontent.com/19485472/52409781-7dab1500-2afc-11e9-8f05-ab53a359cf72.jpg)

AWS SDK API reference personalize.get_metric:
![sdk](https://user-images.githubusercontent.com/19485472/52409376-5a339a80-2afb-11e9-9ebd-82046fb01bca.jpg)

Precision at 5, 10 and 25 are having different values in console and in get_metric api.

Please let me know which one is to be considered as my deployment is dependent on the metric.

Thanks,
Rohan Hodarkar

**Comment by yifeim** [comment]
Thanks for providing the feedback.

The SDK API is more accurate. However, I tend to believe that having three significant digits is sufficient for most applications, for example finding the best recipe for your dataset and application.

Please let us know if you have special use cases or specific expectations.

Thanks.

**Comment by rohanhodarkar** [comment]
I believe you misunderstood me. I am not speaking about the decimal
precision in the matrices.

Check Precision at 5 value in console and in SDK provided screenshots. Both
are different.

**Comment by hyunjoons** [comment]
Thank you for pointing that out! That is a bug in our console. The metrics provided by the SDK are correct. We have fixed the console bug and will be deploying soon. Will close this issue once deployed.

**Comment by sethiv** [comment]
This issue has been resolved.
